var width = 4;
var height = 5;
var area = width * height;
console.log('area:', area);
console.log('typeof area:', typeof area);
var bill = 100;
var payment = 500;
var change = bill - payment;
console.log('change:', change);
console.log('typeof change:', typeof change);
var quizes = 100;
var midterm = 80;
var final = 90;
var grade = (quizes + midterm + final) / 3;
console.log('grade:', grade);
console.log('typeof grade:', typeof grade);
var firstName = 'Eric';
var lastName = 'Fried';
var fullName = firstName + ' ' + lastName;
console.log('fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
var pH = 10;
var isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
var headCount = 10;
var isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
var motto = fullName;
motto += ' is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
